name: ragna_studio

volumes:
  postgres_data:
  redis_data:

services:
  webapp:
    image: ghcr.io/ragna-ai/ragna-studio-webapp:latest
    container_name: ragna_studio_webapp
    restart: always
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net
    depends_on:
      - api

  worker:
    image: ghcr.io/ragna-ai/ragna-studio-worker:latest
    container_name: ragna_studio_worker
    restart: always
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net
    depends_on:
      - postgres
      - redis

  api:
    image: ghcr.io/ragna-ai/ragna-studio-api:latest
    container_name: ragna_studio_api
    restart: always
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net
    depends_on:
      - postgres
      - redis
      - webbrowser

  webbrowser:
    image: ghcr.io/ragna-ai/ragna-studio-webbrowser:latest
    container_name: ragna_studio_webbrowser
    restart: always
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

  postgres:
    image: postgres:18.4-alpine3.24
    container_name: ragna_studio_postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

  redis:
    image: redis:8.8.0-alpine3.23
    container_name: ragna_studio_redis
    restart: always
    command: "redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - redis_data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

networks:
  app_net:
    name: ragna_studio_network
    driver: bridge
