# This is a development override file for docker-compose.

services:
  webapp:
    cpus: 1
    restart: no
    profiles:
      - full
    ports:
      - ${APP_PORT:-3000}:3000

  api:
    cpus: 1
    restart: no
    profiles:
      - full
    environment:
      - LOG_LEVEL=warn
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WEBBROWSER_BASE_URL=http://webbrowser:3011
    ports:
      - ${API_PORT:-3010}:3010

  worker:
    cpus: 1
    restart: no
    profiles:
      - full
    environment:
      - LOG_LEVEL=warn
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SMTP_HOST=host.docker.internal

  webbrowser:
    cpus: 1
    restart: no
    profiles:
      - full
    ports:
      - ${WEBBROWSER_PORT:-3011}:3011

  postgres:
    cpus: 1
    restart: no
    ports:
      - ${DB_PORT:-5432}:5432

  redis:
    cpus: 1
    restart: no
    ports:
      - ${REDIS_PORT:-6379}:6379
