services:
  frontend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragna-frontend.rule=Host(`app.ragna.io`)"
      - "traefik.http.routers.ragna-frontend.entrypoints=https"
      - "traefik.http.services.ragna-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.ragna-frontend.service=ragna-frontend"
      - "traefik.http.routers.ragna-frontend.middlewares=default@file"
      - "traefik.http.routers.ragna-frontend.tls=true"
      - "traefik.http.routers.ragna-frontend.tls.certresolver=http"
      - "traefik.docker.network=traefik_net"
    networks:
      traefik_net:
        ipv4_address: 172.18.7.1

  backend:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragna-backend.rule=Host(`api.ragna.io`)"
      - "traefik.http.routers.ragna-backend.entrypoints=https"
      - "traefik.http.services.ragna-backend.loadbalancer.server.port=3010"
      - "traefik.http.routers.ragna-backend.service=ragna-backend"
      - "traefik.http.routers.ragna-backend.middlewares=default@file"
      - "traefik.http.routers.ragna-backend.tls=true"
      - "traefik.http.routers.ragna-backend.tls.certresolver=http"
      - "traefik.docker.network=traefik_net"
    networks:
      traefik_net:
        ipv4_address: 172.18.7.2

networks:
  traefik_net:
    external: true
