services:
  webapp:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragna-webapp.rule=Host(`app.ragna.io`)"
      - "traefik.http.routers.ragna-webapp.entrypoints=https"
      - "traefik.http.services.ragna-webapp.loadbalancer.server.port=3000"
      - "traefik.http.routers.ragna-webapp.service=ragna-webapp"
      - "traefik.http.routers.ragna-webapp.middlewares=default@file"
      - "traefik.http.routers.ragna-webapp.tls=true"
      - "traefik.http.routers.ragna-webapp.tls.certresolver=http"
      - "traefik.docker.network=traefik_net"
    networks:
      traefik_net:
        ipv4_address: 172.18.7.1

  api:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ragna-api.rule=Host(`api.ragna.io`)"
      - "traefik.http.routers.ragna-api.entrypoints=https"
      - "traefik.http.services.ragna-api.loadbalancer.server.port=3010"
      - "traefik.http.routers.ragna-api.service=ragna-api"
      - "traefik.http.routers.ragna-api.middlewares=default@file"
      - "traefik.http.routers.ragna-api.tls=true"
      - "traefik.http.routers.ragna-api.tls.certresolver=http"
      - "traefik.docker.network=traefik_net"
    networks:
      traefik_net:
        ipv4_address: 172.18.7.2

networks:
  traefik_net:
    external: true
