/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {};
declare global {
  const EffectScope: typeof import('vue').EffectScope;
  const MaizzleConfigKey: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useConfig.js').MaizzleConfigKey;
  const RenderContextKey: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/renderContext.js').RenderContextKey;
  const _setCurrentTemplate: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useCurrentTemplate.js')._setCurrentTemplate;
  const computed: typeof import('vue').computed;
  const createApp: typeof import('vue').createApp;
  const customRef: typeof import('vue').customRef;
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent;
  const defineComponent: typeof import('vue').defineComponent;
  const defineConfig: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/defineConfig.js').defineConfig;
  const effectScope: typeof import('vue').effectScope;
  const getCurrentInstance: typeof import('vue').getCurrentInstance;
  const getCurrentScope: typeof import('vue').getCurrentScope;
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher;
  const h: typeof import('vue').h;
  const inject: typeof import('vue').inject;
  const injectHead: typeof import('@unhead/vue').injectHead;
  const isProxy: typeof import('vue').isProxy;
  const isReactive: typeof import('vue').isReactive;
  const isReadonly: typeof import('vue').isReadonly;
  const isRef: typeof import('vue').isRef;
  const isShallow: typeof import('vue').isShallow;
  const markRaw: typeof import('vue').markRaw;
  const nextTick: typeof import('vue').nextTick;
  const onActivated: typeof import('vue').onActivated;
  const onBeforeMount: typeof import('vue').onBeforeMount;
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount;
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate;
  const onDeactivated: typeof import('vue').onDeactivated;
  const onErrorCaptured: typeof import('vue').onErrorCaptured;
  const onMounted: typeof import('vue').onMounted;
  const onRenderTracked: typeof import('vue').onRenderTracked;
  const onRenderTriggered: typeof import('vue').onRenderTriggered;
  const onScopeDispose: typeof import('vue').onScopeDispose;
  const onServerPrefetch: typeof import('vue').onServerPrefetch;
  const onUnmounted: typeof import('vue').onUnmounted;
  const onUpdated: typeof import('vue').onUpdated;
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup;
  const provide: typeof import('vue').provide;
  const reactive: typeof import('vue').reactive;
  const readonly: typeof import('vue').readonly;
  const ref: typeof import('vue').ref;
  const resolveComponent: typeof import('vue').resolveComponent;
  const shallowReactive: typeof import('vue').shallowReactive;
  const shallowReadonly: typeof import('vue').shallowReadonly;
  const shallowRef: typeof import('vue').shallowRef;
  const toRaw: typeof import('vue').toRaw;
  const toRef: typeof import('vue').toRef;
  const toRefs: typeof import('vue').toRefs;
  const toValue: typeof import('vue').toValue;
  const triggerRef: typeof import('vue').triggerRef;
  const unref: typeof import('vue').unref;
  const useAttrs: typeof import('vue').useAttrs;
  const useBaseUrl: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useBaseUrl.js').useBaseUrl;
  const useConfig: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useConfig.js').useConfig;
  const useCssModule: typeof import('vue').useCssModule;
  const useCssVars: typeof import('vue').useCssVars;
  const useCurrentTemplate: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useCurrentTemplate.js').useCurrentTemplate;
  const useDoctype: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useDoctype.js').useDoctype;
  const useEvent: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useEvent.js').useEvent;
  const useFont: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useFont.js').useFont;
  const useHead: typeof import('@unhead/vue').useHead;
  const useHeadSafe: typeof import('@unhead/vue').useHeadSafe;
  const useId: typeof import('vue').useId;
  const useModel: typeof import('vue').useModel;
  const useOutlookFallback: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useOutlookFallback.js').useOutlookFallback;
  const useOutputPath: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useOutputPath.js').useOutputPath;
  const usePlaintext: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/usePlaintext.js').usePlaintext;
  const usePreheader: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/usePreheader.js').usePreheader;
  const useSeoMeta: typeof import('@unhead/vue').useSeoMeta;
  const useSlots: typeof import('vue').useSlots;
  const useTemplateRef: typeof import('vue').useTemplateRef;
  const useTransformers: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useTransformers.js').useTransformers;
  const useUrlQuery: typeof import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useUrlQuery.js').useUrlQuery;
  const watch: typeof import('vue').watch;
  const watchEffect: typeof import('vue').watchEffect;
  const watchPostEffect: typeof import('vue').watchPostEffect;
  const watchSyncEffect: typeof import('vue').watchSyncEffect;
}
// for type re-export
declare global {
  // @ts-ignore
  export type {
    Component,
    Slot,
    Slots,
    ComponentPublicInstance,
    ComputedRef,
    DirectiveBinding,
    ExtractDefaultPropTypes,
    ExtractPropTypes,
    ExtractPublicPropTypes,
    InjectionKey,
    PropType,
    Ref,
    ShallowRef,
    MaybeRef,
    MaybeRefOrGetter,
    VNode,
    WritableComputedRef,
  } from 'vue';
  import('vue');
  // @ts-ignore
  export type {
    FontRegistration,
    RenderContext,
    TailwindBlock,
  } from '../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/renderContext.d';
  import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/renderContext.d');
  // @ts-ignore
  export type {
    FontProvider,
    UseFontOptions,
  } from '../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useFont.d';
  import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/useFont.d');
  // @ts-ignore
  export type { UsePlaintextOptions } from '../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/usePlaintext.d';
  import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/usePlaintext.d');
  // @ts-ignore
  export type { UsePreheaderOptions } from '../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/usePreheader.d';
  import('../../../node_modules/.pnpm/@maizzle+framework@6.0.1_@nuxt+kit@4.4.8_magicast@0.5.2__@types+node@24.1.0_@vue+compil_270c30f381151942f1f76dc0801a0694/node_modules/@maizzle/framework/dist/composables/usePreheader.d');
}
