#!/usr/bin/env node
// Regenerates docs/INDEX.md from the `Status: ...` line each PRD/design doc
// carries under its H1, per the status vocabulary in docs/README.md. Docs
// without a Status line are reference material (known-issues, strategy
// notes, reviews) and are intentionally left out.
// Run: pnpm docs:index

import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const docsDir = join(import.meta.dirname, '..', 'docs');
const outFile = join(docsDir, 'INDEX.md');

const HEADING_LINE = /^#\s+(.+)/;

// The six canonical values from docs/README.md, ordered by how useful they
// are to see first: active work, then backlog, then shipped reference,
// then dead/historical. A status that doesn't lead with one of these
// (e.g. a checklist's "snapshot") falls into "Other".
const CANONICAL_STATUSES = ['in-progress', 'decided', 'proposed', 'implemented', 'deferred', 'superseded'];

function stripFrontmatter(lines) {
  if (lines[0]?.trim() !== '---') return lines;
  const closingIndex = lines.slice(1).findIndex((line) => line.trim() === '---');
  return closingIndex === -1 ? lines : lines.slice(closingIndex + 2);
}

function findMarkdownFiles(dir) {
  const files = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    if (statSync(fullPath).isDirectory()) {
      files.push(...findMarkdownFiles(fullPath));
    } else if (entry.endsWith('.md') && entry !== 'INDEX.md' && entry !== 'README.md') {
      files.push(fullPath);
    }
  }
  return files;
}

function findTitle(lines) {
  for (const line of lines.slice(0, 5)) {
    const match = HEADING_LINE.exec(line.trim());
    if (match) return match[1].trim();
  }
  return undefined;
}

function findStatus(lines) {
  const statusLineIndex = lines.findIndex((line, i) => i < 20 && /status:/i.test(line));
  if (statusLineIndex === -1) return undefined;

  const paragraph = [lines[statusLineIndex]];
  for (let i = statusLineIndex + 1; i < lines.length; i++) {
    if (lines[i].trim() === '') break;
    paragraph.push(lines[i]);
  }

  let text = paragraph
    .join(' ')
    .replace(/^.*status:\s*/i, '')
    .replace(/>/g, '')
    .replace(/\*\*/g, '')
    .replace(/\s+/g, ' ')
    .trim();

  // Keep only the first sentence: the rest is prose explaining the status,
  // not the status itself, and would blow up the table row.
  const sentenceEnd = text.indexOf('. ');
  if (sentenceEnd !== -1) text = text.slice(0, sentenceEnd);
  else if (text.endsWith('.')) text = text.slice(0, -1);

  return text;
}

function parseDoc(filePath) {
  const lines = stripFrontmatter(readFileSync(filePath, 'utf8').split('\n'));
  return {
    title: findTitle(lines) ?? relative(docsDir, filePath),
    status: findStatus(lines),
    path: relative(docsDir, filePath),
  };
}

// The leading word (or hyphenated word) of the status text must be one of
// docs/README.md's six canonical values; anything else groups as "Other" so
// non-compliant docs stay visible instead of silently miscategorized.
function groupFor(status) {
  const leadingWord = /^[a-z-]+/i.exec(status)?.[0].toLowerCase();
  return CANONICAL_STATUSES.includes(leadingWord) ? leadingWord : 'other';
}

const docs = findMarkdownFiles(docsDir)
  .map(parseDoc)
  .filter((doc) => doc.status);

const byGroup = new Map([...CANONICAL_STATUSES.map((s) => [s, []]), ['other', []]]);
for (const doc of docs) {
  byGroup.get(groupFor(doc.status)).push(doc);
}

const GROUP_LABELS = {
  'in-progress': 'In progress',
  decided: 'Decided',
  proposed: 'Proposed',
  implemented: 'Implemented',
  deferred: 'Deferred',
  superseded: 'Superseded',
  other: 'Other (non-standard status — see docs/README.md)',
};

const lines = [
  '# Docs index',
  '',
  `Generated by \`pnpm docs:index\` on ${new Date().toISOString().slice(0, 10)}. Do not hand-edit; run the script instead.`,
  '',
  'Only docs that carry a `Status: ...` line under their H1 are listed here,',
  'per the status vocabulary in [README.md](./README.md). Reference material',
  '(known-issues, strategy notes, reviews) has no status and is intentionally',
  'left out. Sections are ordered by how actionable the status is: active',
  'work first, shipped reference and dead/historical docs last.',
  '',
];

for (const key of [...CANONICAL_STATUSES, 'other']) {
  const items = byGroup.get(key);
  if (items.length === 0) continue;
  items.sort((a, b) => a.path.localeCompare(b.path));
  lines.push(`## ${GROUP_LABELS[key]}`, '', '| Doc | Status |', '| --- | --- |');
  for (const doc of items) {
    lines.push(`| [${doc.title}](./${doc.path}) | ${doc.status} |`);
  }
  lines.push('');
}

writeFileSync(outFile, lines.join('\n'));
console.log(`Wrote ${relative(process.cwd(), outFile)} (${docs.length} docs indexed)`);
